from models.CoLA_model import CoLAModel
from models.MNLIM_model import MNLIMModel
from models.MNLIMM_model import MNLIMMModel
from models.MRPC_model import MRPCModel
from models.QNLI_model import QNLIModel
from models.QQP_model import QQPModel
from models.RTE_model import RTEModel
from models.SST2_model import SST2Model
from models.STSB_model import STSBModel
from models.WNLI_model import WNLIModel
